name: Build, Publish and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: windows-latest
    permissions:
      contents: write
      # This is required for PyPI publishing
      id-token: write 
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install pyinstaller and project in editable mode
          pip install pyinstaller build
          pip install -e .

      - name: Build enea_downloader executable
        run: pyinstaller --onefile --console --name enea_downloader --hidden-import=eanalizer enea-downloader

      - name: Build eanalizer executable
        run: pyinstaller --onefile --console --name eanalizer-cli --hidden-import=eanalizer eanalizer-cli

      - name: Test the eanalizer executable
        env:
          PYTHONUTF8: "1"
        run: dist/eanalizer-cli.exe --help
      
      - name: Build sdist and wheel
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # You will need to create a PYPI_API_TOKEN secret in your repository settings
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Create Release and Upload EXE Assets
        uses: softprops/action-gh-release@v2
        with:
          # This action will create a release for the pushed tag
          # and upload the specified files as assets.
          files: |
            dist/enea_downloader.exe
            dist/eanalizer-cli.exe